#!/bin/bash
################################################################################
################################################################################
####                                                                       #####
#### A notice to all nerds.                                                #####
#### If you will copy developers real work it will not make you a hacker.  #####
#### Resepect all developers, we doing this because it's fun!              #####
####                                                                       #####
################################################################################
################################ SOURCE CODE ###################################
################################################################################
################################################################################
####                                                                       #####
####  Copyright (C) 2018-2019, wuseman                                     #####
####                                                                       #####
####  This program is free software; you can redistribute it and/or modify #####
####  it under the terms of the GNU General Public License as published by #####
####  the Free Software Foundation; either version 2 of the License, or    #####
####  (at your option) any later version.                                  #####
####                                                                       #####
####  This program is distributed in the hope that it will be useful,      #####
####  but WITHOUT ANY WARRANTY; without even the implied warranty of       #####
####  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the        #####
####  GNU General Public License for more details.                         #####
####                                                                       #####
####  You must obey the GNU General Public License. If you will modify     #####
####  this file(s), you may extend this exception to your version          #####
####  of the file(s), but you are not obligated to do so.  If you do not   #####
####  wish to do so, delete this exception statement from your version.    #####
####  If you delete this exception statement from all source files in the  #####
####  program, then also delete it here.                                   #####
####                                                                       #####
####  Contact:                                                             #####
####          IRC: Freenode @ wuseman                                      #####
####          Mail: wuseman <wuseman@nr1.nu>                               #####
####                                                                       #####
################################################################################
################################################################################

TDIR="/home/wuseman/websites"

if [[ -z $TDIR ]]; then
   printf "Please set a target dir for the folders that will be downloaded...\n"
   exit 1
fi

usage() {
cat << EOF

 Usage: ./wmirror.sh -u <url> [options]

     -u|--url   <url>                       - This option is required and will set the url to target" 
     -d|--depth <0-99>                      - Set a depth value for how many folders you wanna download...(Default: 5).
     -q|--quiet <1>                       - Mirror the site without spamming to stdout, only use -q 1 if you want it to be quiet

EOF
exit 1
}

if [[ -z $1 ]]; then usage;exit 1; fi


while getopts "u:d:q:h" getopts; do
  case $getopts in
    h) usage ;;
    u) u=$OPTARG ;;
    d) d=$OPTARG
         if [[ $d != [0-9] ]] && [[ $d != [0-9][0-9] ]]; then
	 if [[ $d = [A-Za-z].* ]]; then
	   printf "[\e[0;31m+\e[0m] - Depth must be used by a number...\n"
	   exit 1
	 fi
	   printf "[\e[0;31m+\e[0m] - That's not a valid number, largest depth is 99..\n"
	   exit 1
	 fi  ;;
    q) q=$OPTARG
       (( q == 1 )) || usage ;;
    \?) printf "[\e[0;31m+\e[0m] - Internal Error!"; exit 1 ;; 
    *) printf "[\e[0;31m+\e[0m] - That's not a valid url.."; exit 1 ;;
  esac
done

if [[ $q = "1" ]]; then
       read -p "Please enter a description of this site: " DESC
       echo -e "- $(date +%d-%m-%Y) | $(date +%H:%M:%S) | $u | $DESC" >> $TDIR/website_sites.txt
       echo "Downloading $u..."
       wget -nc -e robots=off -r -q $u -P "$TDIR"
       printf "\e[7m%-`tput cols`s\e[0m\n" "Successfully mirrored: $u "
       exit 1
fi
       read -p "Please enter a description of this site: " DESC
       echo -e "- $(date +%d-%m-%Y) | $(date +%H:%M:%S) | $u | $DESC" >> $TDIR/website_sites.txt
       echo "Downloading $u..."
       wget -nc -q -e robots=off -r --show-progress $u -P "$TDIR/"
       printf "\e[7m%-`tput cols`s\e[0m\n" "Successfully mirrored: $u "
       exit 1
