#!/bin/bash
VERSION=1.2
################################################################################
################################################################################
####                                                                       #####
#### A notice to all nerds.                                                #####
#### If you will copy developers real work it will not make you a hacker.  #####
#### Resepect all developers, we doing this because it's fun!              #####
####                                                                       #####
################################################################################
################################ SOURCE CODE ###################################
################################################################################
################################################################################
####                                                                       #####
####  Copyright (C) 2018-2019, wuseman                                     #####
####                                                                       #####
####  This program is free software; you can redistribute it and/or modify #####
####  it under the terms of the GNU General Public License as published by #####
####  the Free Software Foundation; either version 2 of the License, or    #####
####  (at your option) any later version.                                  #####
####                                                                       #####
####  This program is distributed in the hope that it will be useful,      #####
####  but WITHOUT ANY WARRANTY; without even the implied warranty of       #####
####  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the        #####
####  GNU General Public License for more details.                         #####
####                                                                       #####
####  You must obey the GNU General Public License. If you will modify     #####
####  this file(s), you may extend this exception to your version          #####
####  of the file(s), but you are not obligated to do so.  If you do not   #####
####  wish to do so, delete this exception statement from your version.    #####
####  If you delete this exception statement from all source files in the  #####
####  program, then also delete it here.                                   #####
####                                                                       #####
####  Contact:                                                             #####
####          IRC: Freenode @ wuseman                                      #####
####          Mail: wuseman <wuseman@nr1.nu>                               #####
####                                                                       #####
################################################################################
################################################################################

# MIRROR A SITE
# ADD THIS TO SCRIPT LATER:

# wget --no-parent --timestamping --convert-links --page-requisites --no-directories --no-host-directories -erobots=off http://domain.tld/webpage.html
# or
# wget -E -H -k -K -p http://www.example.com/
# or
# wget -r -N -l inf --no-remove-listing
# or below from: https://github.com/webjay/webtography/blob/master/lib/wget.js#L15-L26
# --user-agent=Webtography
# --no-cookies
# --timestamping
# --recursive
# --level=1
# --convert-links 
# --no-parent
# --page-requisites
# --adjust-extension
# --max-redirect=0
# --exclude-directories=blog

## A more complex way, from: https://handyman.dulare.com/advanced-wget-website-mirroring/

# wget --mirror --convert-links --adjust-extension --page-requisites --span-hosts -U Mozilla -e robots=off --no-cookies -D www.mywebsite.com,files.mywebsite.com,images.somewhere.com http://www.mywebsite.com/
# wget --mirror --convert-links --adjust-extension --page-requisites --span-hosts -D www.mywebsite.com,files.mywebsite.com,images.somewhere.com http://www.mywebsite.com/


# 
# wget -m -np -p $url
# -p to download everything required to display a page is useful.

usage() {
cat << EOF

 Usage: ./wmirror.sh -u <url> [options]

     -h                 - Print this useful help
     -u                 - This option is required and will set the url to target" 
     -p                 - Path to save your downloaded data
     -v                 - Print installed version

EOF
exit 1
}

if [[ -z $1 ]]; then usage;exit 1; fi


while getopts ":u:p:vh" getopts; do
  case $getopts in
    u) u=$OPTARG ;;
    p) p=$OPTARG ;;
    h) usage ;;
    v) echo -e "$basename$0: v$VERSION"; exit 1 ;;
    \?) echo -e "$basename$0: internal error -- $* is not a valid option, exiting ...;" exit 1 ;; 
    *) echo -e "$basename$0: internal error -- $* is not a valid option, exiting ...;" exit 1 ;; 
  esac
done

echo -e "-------------------------------------"
echo -e "Downloading $u ....."
echo -e "-------------------------------------"
wget -q --show-progress -l inf -m -e robots=off -P $p $u


